# Generated by Django 5.1.3 on 2024-11-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionInmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inmueble',
            options={'permissions': [('puede_ver_inmuebles', 'Puede ver inmuebles'), ('puede_ver_detalle_inmuebles', 'Puede ver detalle de inmuebles'), ('puede_publicar_inmuebles', 'Puede publicar inmuebles')]},
        ),
    ]
