# Generated by Django 5.1.3 on 2024-11-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionInmuebles', '0002_comuna_region_alter_inmueble_comuna_comuna_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
    ]
